namespace ECoffee.Presentation.Forms
{
    partial class MenuEditorForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            tableLayoutPanel1 = new TableLayoutPanel(); lTitle = new Label(); label1 = new Label(); label2 = new Label(); label3 = new Label(); label4 = new Label(); label5 = new Label(); label6 = new Label(); tbName = new TextBox(); tbCategory = new TextBox(); nudSmall = new NumericUpDown(); nudMedium = new NumericUpDown(); nudLarge = new NumericUpDown(); nudQuantity = new NumericUpDown(); nudReorder = new NumericUpDown(); panelButtons = new FlowLayoutPanel(); bSave = new Button(); bCancel = new Button(); tableLayoutPanel1.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)nudSmall).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudMedium).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudLarge).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudQuantity).BeginInit(); ((System.ComponentModel.ISupportInitialize)nudReorder).BeginInit(); panelButtons.SuspendLayout(); SuspendLayout();
            tableLayoutPanel1.ColumnCount=2; tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,160F)); tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F)); tableLayoutPanel1.Controls.Add(lTitle,0,0); tableLayoutPanel1.SetColumnSpan(lTitle,2); tableLayoutPanel1.Controls.Add(label1,0,1); tableLayoutPanel1.Controls.Add(tbName,1,1); tableLayoutPanel1.Controls.Add(label2,0,2); tableLayoutPanel1.Controls.Add(tbCategory,1,2); tableLayoutPanel1.Controls.Add(label3,0,3); tableLayoutPanel1.Controls.Add(nudSmall,1,3); tableLayoutPanel1.Controls.Add(label4,0,4); tableLayoutPanel1.Controls.Add(nudMedium,1,4); tableLayoutPanel1.Controls.Add(label5,0,5); tableLayoutPanel1.Controls.Add(nudLarge,1,5); tableLayoutPanel1.Controls.Add(label6,0,6); tableLayoutPanel1.Controls.Add(nudQuantity,1,6); tableLayoutPanel1.Controls.Add(new Label(){Text="Mức nhập lại",Anchor=AnchorStyles.Left,AutoSize=true},0,7); tableLayoutPanel1.Controls.Add(nudReorder,1,7); tableLayoutPanel1.Controls.Add(panelButtons,0,8); tableLayoutPanel1.SetColumnSpan(panelButtons,2); tableLayoutPanel1.Dock=DockStyle.Fill; tableLayoutPanel1.Padding = new Padding(16); tableLayoutPanel1.RowCount=9;
            lTitle.AutoSize=true; lTitle.Font=new Font("Segoe UI",16F,FontStyle.Bold); lTitle.Text="Thông tin món"; label1.Text="Tên món"; label2.Text="Loại nước"; label3.Text="Giá Small"; label4.Text="Giá Medium"; label5.Text="Giá Large"; label6.Text="Tồn kho";
            foreach(var c in new Control[]{label1,label2,label3,label4,label5,label6}){c.Anchor=AnchorStyles.Left; c.AutoSize=true;}
            tbName.Dock=DockStyle.Fill; tbCategory.Dock=DockStyle.Fill; nudSmall.Dock=DockStyle.Left; nudMedium.Dock=DockStyle.Left; nudLarge.Dock=DockStyle.Left; nudQuantity.Dock=DockStyle.Left; nudReorder.Dock=DockStyle.Left; nudSmall.Maximum=nudMedium.Maximum=nudLarge.Maximum=100000000; nudQuantity.Maximum=nudReorder.Maximum=1000000;
            panelButtons.Dock=DockStyle.Fill; panelButtons.FlowDirection=FlowDirection.RightToLeft; panelButtons.Controls.AddRange(new Control[]{bSave,bCancel}); bSave.Text="Lưu"; bSave.Click += bSave_Click; bCancel.Text="Hủy"; bCancel.Click += bCancel_Click;
            AutoScaleDimensions = new SizeF(9F,21F); AutoScaleMode = AutoScaleMode.Font; ClientSize = new Size(560,450); Controls.Add(tableLayoutPanel1); Font = new Font("Segoe UI",12F); FormBorderStyle=FormBorderStyle.FixedDialog; MaximizeBox=false; MinimizeBox=false; StartPosition=FormStartPosition.CenterParent; Load += MenuEditorForm_Load; Text="Thông tin món"; tableLayoutPanel1.ResumeLayout(false); tableLayoutPanel1.PerformLayout(); ((System.ComponentModel.ISupportInitialize)nudSmall).EndInit(); ((System.ComponentModel.ISupportInitialize)nudMedium).EndInit(); ((System.ComponentModel.ISupportInitialize)nudLarge).EndInit(); ((System.ComponentModel.ISupportInitialize)nudQuantity).EndInit(); ((System.ComponentModel.ISupportInitialize)nudReorder).EndInit(); panelButtons.ResumeLayout(false); ResumeLayout(false);
        }
        #endregion
        private TableLayoutPanel tableLayoutPanel1; private Label lTitle; private Label label1; private Label label2; private Label label3; private Label label4; private Label label5; private Label label6; private TextBox tbName; private TextBox tbCategory; private NumericUpDown nudSmall; private NumericUpDown nudMedium; private NumericUpDown nudLarge; private NumericUpDown nudQuantity; private NumericUpDown nudReorder; private FlowLayoutPanel panelButtons; private Button bSave; private Button bCancel;
    }
}
