namespace ECoffee.Presentation.Forms
{
    partial class PaymentManagementForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            tableLayoutPanel1 = new TableLayoutPanel(); panelHeader = new Panel(); lHeader = new Label(); panelActions = new FlowLayoutPanel(); bCreate = new Button(); bView = new Button(); bQr = new Button(); bCheckSuccess = new Button(); bRefresh = new Button(); tbSearch = new TextBox(); bSearch = new Button(); splitContainer1 = new SplitContainer(); lbMethods = new ListBox(); dgvPayments = new DataGridView(); colPid = new DataGridViewTextBoxColumn(); colOrderId = new DataGridViewTextBoxColumn(); colMethod = new DataGridViewTextBoxColumn(); colAmount = new DataGridViewTextBoxColumn(); colStatus = new DataGridViewTextBoxColumn(); colRef = new DataGridViewTextBoxColumn(); colCreated = new DataGridViewTextBoxColumn(); tableLayoutPanel1.SuspendLayout(); panelHeader.SuspendLayout(); panelActions.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)splitContainer1).BeginInit(); splitContainer1.Panel1.SuspendLayout(); splitContainer1.Panel2.SuspendLayout(); splitContainer1.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)dgvPayments).BeginInit(); SuspendLayout();
            tableLayoutPanel1.ColumnCount=1; tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100F)); tableLayoutPanel1.Controls.Add(panelHeader,0,0); tableLayoutPanel1.Controls.Add(splitContainer1,0,1); tableLayoutPanel1.Dock=DockStyle.Fill; tableLayoutPanel1.RowCount=2; tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Absolute,120F)); tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent,100F));
            panelHeader.Controls.Add(panelActions); panelHeader.Controls.Add(lHeader); panelHeader.Dock=DockStyle.Fill; lHeader.AutoSize=true; lHeader.Font=new Font("Segoe UI",16F,FontStyle.Bold); lHeader.Location=new Point(16,16); lHeader.Text="Quản lý Thanh toán";
            panelActions.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right; panelActions.Controls.AddRange(new Control[]{bCreate,bView,bQr,bCheckSuccess,bRefresh,tbSearch,bSearch}); panelActions.Location=new Point(16,58); panelActions.Size=new Size(1040,40); bCreate.Text="Tạo payment"; bCreate.Click+=bCreate_Click; bView.Text="Xem"; bView.Click+=bView_Click; bQr.Text="Tạo QR"; bQr.Click+=bQr_Click; bCheckSuccess.Text="Check thành công"; bCheckSuccess.Click+=bCheckSuccess_Click; bRefresh.Text="Tải lại"; bRefresh.Click+=bRefresh_Click; tbSearch.PlaceholderText="Tìm theo OrderId / method / status"; tbSearch.Width=320; bSearch.Text="Tìm"; bSearch.Click+=bSearch_Click;
            splitContainer1.Dock=DockStyle.Fill; splitContainer1.SplitterDistance=220; splitContainer1.Panel1.Controls.Add(lbMethods); splitContainer1.Panel2.Controls.Add(dgvPayments);
            lbMethods.Dock=DockStyle.Fill; lbMethods.IntegralHeight=false; lbMethods.Font=new Font("Segoe UI",12F); 
            dgvPayments.AllowUserToAddRows=false; dgvPayments.AllowUserToDeleteRows=false; dgvPayments.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; dgvPayments.BackgroundColor=Color.White; dgvPayments.ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.AutoSize; dgvPayments.Columns.AddRange(new DataGridViewColumn[]{colPid,colOrderId,colMethod,colAmount,colStatus,colRef,colCreated}); dgvPayments.Dock=DockStyle.Fill; dgvPayments.MultiSelect=false; dgvPayments.ReadOnly=true; dgvPayments.SelectionMode=DataGridViewSelectionMode.FullRowSelect; dgvPayments.CellDoubleClick += dgvPayments_CellDoubleClick;
            colPid.DataPropertyName="Id"; colPid.HeaderText="Id"; colPid.FillWeight=45; colOrderId.DataPropertyName="OrderId"; colOrderId.HeaderText="OrderId"; colMethod.DataPropertyName="Method"; colMethod.HeaderText="Method"; colAmount.DataPropertyName="Amount"; colAmount.HeaderText="Amount"; colStatus.DataPropertyName="Status"; colStatus.HeaderText="Status"; colRef.DataPropertyName="TransactionRef"; colRef.HeaderText="TransactionRef"; colCreated.DataPropertyName="CreatedAt"; colCreated.HeaderText="Created";
            AutoScaleDimensions = new SizeF(9F,21F); AutoScaleMode=AutoScaleMode.Font; ClientSize=new Size(1180,680); Controls.Add(tableLayoutPanel1); Font=new Font("Segoe UI",12F); StartPosition=FormStartPosition.CenterParent; Text="Quản lý Thanh toán"; Load += PaymentManagementForm_Load; tableLayoutPanel1.ResumeLayout(false); panelHeader.ResumeLayout(false); panelHeader.PerformLayout(); panelActions.ResumeLayout(false); panelActions.PerformLayout(); splitContainer1.Panel1.ResumeLayout(false); splitContainer1.Panel2.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)splitContainer1).EndInit(); splitContainer1.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)dgvPayments).EndInit(); ResumeLayout(false);
        }
        #endregion
        private TableLayoutPanel tableLayoutPanel1; private Panel panelHeader; private Label lHeader; private FlowLayoutPanel panelActions; private Button bCreate; private Button bView; private Button bQr; private Button bCheckSuccess; private Button bRefresh; private TextBox tbSearch; private Button bSearch; private SplitContainer splitContainer1; private ListBox lbMethods; private DataGridView dgvPayments; private DataGridViewTextBoxColumn colPid; private DataGridViewTextBoxColumn colOrderId; private DataGridViewTextBoxColumn colMethod; private DataGridViewTextBoxColumn colAmount; private DataGridViewTextBoxColumn colStatus; private DataGridViewTextBoxColumn colRef; private DataGridViewTextBoxColumn colCreated;
    }
}
